server:
  port: 0
spring:
  application:
    name: users-service
#  security:
#    basic:
#      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/tramways_users?useLegacyDatetimeCode=false&serverTimezone=Europe/Rome
    username: tramways
    password: tramways

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
